# Generated by Django 4.1.3 on 2023-01-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='article_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
